version: "3.8"

services:
  php-fpm-publisher:
    container_name: php-fpm-publisher
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/
    depends_on:
      - postgres-publisher
      - postgres-publisher-test
    networks:
      - app-network

  nginx-publisher:
    container_name: nginx-publisher
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm-publisher
      - postgres-publisher-test
    networks:
      - app-network

  postgres-publisher:
    container_name: postgres-publisher
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  postgres-publisher-test:
    container_name: postgres-publisher-test
    build:
      context: ./postgres
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:

